CREATE TABLE "airline" (
	"id" serial PRIMARY KEY NOT NULL,
	"name" varchar(64) NOT NULL,
	"iata_code" varchar(3) NOT NULL,
	"country" varchar(32) NOT NULL,
	CONSTRAINT "airline_iata_code_unique" UNIQUE("iata_code")
);
INSERT INTO "airline" ("name", "iata_code", "country") 
VALUES
	('American Airlines', 'AA', 'United States'),
  ('Delta Airlines', 'DL', 'United States'),
  ('United Airlines', 'UA', 'United States'),
  ('Southwest Airlines', 'WN', 'United States'),
  ('Alaska Airlines', 'AS', 'United States'),
  ('JetBlue Airways', 'B6', 'United States'),
  ('Air Canada', 'AC', 'Canada'),
  ('WestJet', 'WS', 'Canada'),
  ('Air Transat', 'TS', 'Canada'),
  ('Porter Airlines', 'PD', 'Canada'),
  ('Sunwing Airlines', 'WG', 'Canada'),
  ('Flair Airlines', 'F8', 'Canada'),
  ('Lufthansa', 'LH', 'Germany'),
  ('Eurowings', 'EW', 'Germany'),
  ('Condor', 'DE', 'Germany'),
  ('TUI Fly Deutschland', 'X3', 'Germany'),
  ('German Airways', 'GW', 'Germany'),
  ('Air Hamburg', 'HH', 'Germany'),
  ('British Airways', 'BA', 'United Kingdom'),
  ('EasyJet', 'U2', 'United Kingdom'),
  ('Virgin Atlantic', 'VS', 'United Kingdom'),
  ('Jet2.com', 'LS', 'United Kingdom'),
  ('Loganair', 'LM', 'United Kingdom'),
  ('Flybe', 'BE', 'United Kingdom'),
  ('Air France', 'AF', 'France'),
  ('Corsair', 'SS', 'France'),
  ('XL Airways France', 'SE', 'France'),
  ('Aigle Azur', 'ZI', 'France'),
  ('French Bee', 'BF', 'France'),
  ('Air Caraïbes', 'TX', 'France'),
  ('KLM', 'KL', 'Netherlands'),
  ('Transavia', 'HV', 'Netherlands'),
  ('TUI fly Netherlands', 'OR', 'Netherlands'),
  ('Corendon Dutch Airlines', 'CD', 'Netherlands'),
  ('Amsterdam Airlines', 'AM', 'Netherlands'),
  ('Martinair', 'MP', 'Netherlands'),
  ('Qatar Airways', 'QR', 'Qatar'),
  ('Gulf Air', 'GF', 'Qatar'),
  ('Al Maha Airways', 'MH', 'Qatar'),
  ('Qatar Executive', 'QE', 'Qatar'),
  ('Jazeera Airways', 'J9', 'Qatar'),
  ('Flydubai', 'FZ', 'Qatar'),
  ('Emirates', 'EK', 'United Arab Emirates'),
  ('Etihad Airways', 'EY', 'United Arab Emirates'),
  ('Air Arabia', 'AB', 'United Arab Emirates'),
  ('Flydubai', 'FDB', 'United Arab Emirates'),
  ('Wizz Air Abu Dhabi', '5W', 'United Arab Emirates'),
  ('Royal Jet', 'RJ', 'United Arab Emirates'),
  ('Singapore Airlines', 'SQ', 'Singapore'),
  ('Scoot', 'TR', 'Singapore'),
  ('Jetstar Asia', '3K', 'Singapore'),
  ('SilkAir', 'MI', 'Singapore'),
  ('Valuair', 'VF', 'Singapore'),
  ('Tiger Airways', 'IT', 'Singapore');
